[package]
name = "reddit"
version = "0.1.0"
authors = ["keatinge <willy.keatinge@gmail.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
hyper-tls = "0.1.2"
scraper = "0.4.0"
futures-cpupool = "0.1"